param(
    [string]$SourceDir = (Join-Path $PSScriptRoot ".."),
    [string]$OutputDir = (Join-Path $PSScriptRoot "..\dist")
)

$ErrorActionPreference = "Stop"

$resolvedSourceDir = (Resolve-Path $SourceDir).Path
if (!(Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir | Out-Null
}
$resolvedOutputDir = (Resolve-Path $OutputDir).Path

$manifestPath = Join-Path $resolvedSourceDir "manifest.json"
$version = "0.0.0"
if (Test-Path $manifestPath) {
    $manifest = Get-Content -Path $manifestPath -Raw | ConvertFrom-Json
    if ($manifest.version) {
        $version = $manifest.version
    }
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmm"
$packageName = "HTMLFusiontoCitizen-v$version-$timestamp"
$stagingRoot = Join-Path $resolvedOutputDir "_staging"
$stagingDir = Join-Path $stagingRoot $packageName
$zipPath = Join-Path $resolvedOutputDir "$packageName.zip"
$latestZipPath = Join-Path $resolvedOutputDir "HTMLFusiontoCitizen-latest.zip"

if (Test-Path $stagingRoot) {
    Remove-Item -Path $stagingRoot -Recurse -Force
}
if (Test-Path $zipPath) {
    Remove-Item -Path $zipPath -Force
}

New-Item -ItemType Directory -Path $stagingDir -Force | Out-Null

$itemsToCopy = @(
    "manifest.json",
    "README.md",
    "main.py",
    "mainApplication.py",
    "Citizen.py",
    "Citizen.manifest",
    "citizen_selector.html",
    "machines.txt",
    "html",
    "posts",
    "resources",
    "template"
)

foreach ($item in $itemsToCopy) {
    $sourcePath = Join-Path $resolvedSourceDir $item
    if (Test-Path $sourcePath) {
        Copy-Item -Path $sourcePath -Destination $stagingDir -Recurse -Force
    }
    else {
        Write-Warning "Skipped missing item: $item"
    }
}

$installNotesPath = Join-Path $stagingDir "INSTALL.txt"
$installNotes = @"
Citizen Post Processor Add-in Install

1. Unzip this package.
2. Copy the folder '$packageName' to:
   $env:APPDATA\Autodesk\Autodesk Fusion 360\API\AddIns
3. In Fusion 360, open Utilities -> Add-Ins and select the add-in folder.
4. Run the add-in.

Notes
- If updating from a previous version, replace the old folder with the new one.
- This package was generated by scripts/create-release-package.ps1.
"@
Set-Content -Path $installNotesPath -Value $installNotes -Encoding ASCII

Compress-Archive -Path $stagingDir -DestinationPath $zipPath -CompressionLevel Optimal -Force
Copy-Item -Path $zipPath -Destination $latestZipPath -Force

Remove-Item -Path $stagingRoot -Recurse -Force

Write-Host "Created package: $zipPath"
Write-Host "Updated latest package: $latestZipPath"
